# Generated by Django 4.2.7 on 2023-11-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
